In [8]:
import numpy as np

In [9]:
ar1 = np.random.randint(0,100,12)
ar1

array([36, 49, 28, 31,  8, 37, 74, 31, 63, 94, 15, 59], dtype=int32)

In [10]:
ar1.min()

np.int32(8)

In [11]:
ar1.argmin() # returns the index of min number in the array

np.int64(4)

In [12]:
ar1.max()

np.int32(94)

In [13]:
ar1.argmax() # returns the index of max number in the array

np.int64(9)

# Size

In [14]:
ar1

array([36, 49, 28, 31,  8, 37, 74, 31, 63, 94, 15, 59], dtype=int32)

In [15]:
ar1.size

12

In [16]:
ar1_2 = ar1.reshape(3,4)
ar1_2

array([[36, 49, 28, 31],
       [ 8, 37, 74, 31],
       [63, 94, 15, 59]], dtype=int32)

In [ ]:
ar1_2.size # when we reshape the array, the size of it does not change

12

In [18]:
len(ar1_2) # it retuns the row number 

3

# Itemsize

In [19]:
ar1_2.dtype

dtype('int32')

# Copy()

In [21]:
ar2 = np.arange(1, 17).reshape(-1, 4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
ar2_copy = ar2.copy()
ar2_copy

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Transpose()

In [23]:
ar2_copy

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
ar2_copy.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [25]:
ar2_copy.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [26]:
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Concatenation of the Arrays

### concatenate()

In [ ]:
# axis = 0 --> rows
# if you would like to concatenate the rows your arrays column numbers should be the same 
# if you would like to concatenate the columns your arrays row numbers should be the same 
# otherwise you cannot concatenate

In [28]:
arr1 = np.arange(1, 7)
arr1

array([1, 2, 3, 4, 5, 6])

In [29]:
arr2 = np.arange(7, 13)
arr2

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
arr1_2 = np.concatenate((arr1, arr2))
arr1_2 # you can only concatenate 1D arrays next to eachother 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# in one dimentional arrays there are no rows or columns
# so we cant create a row in it 

In [31]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [32]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [33]:
a_b = np.concatenate((a, b))
a_b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
a_b = np.concatenate((a, b), axis = 1)
a_b

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# when we use axis 0 it means it puts the arrays bottom of each other -> rows increased
# when we use axis 1 it means it puts the arrays next to each other -> columns increased

In [35]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [36]:
y = np.array([[5, 6], [7, 8], [9, 10]])
y

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
xy = np.concatenate((x, y), axis = 1)
xy

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [42]:
xy = np.concatenate((x, y), axis = None)
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Splitting of the Arrays

### split()
### array_split()
### vsplit()
### hsplit()

In [43]:
ar1 = np.arange(1,9)
ar1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.split(ar1, 2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [49]:
np.array_split(ar1, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [52]:
np.split(ar1,[4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [53]:
np.split(ar1,[5]) 

[array([1, 2, 3, 4, 5]), array([6, 7, 8])]

In [54]:
np.split(ar1,[2])

[array([1, 2]), array([3, 4, 5, 6, 7, 8])]

In [55]:
ar2 = np.arange(1,18)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [56]:
np.split(ar2,[6])

[array([1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [57]:
np.split(ar2,[4,9])

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17])]

In [58]:
ar3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.split(ar3, [1])

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [61]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.split(ar3,[1], axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [62]:
np.split(ar3,[1,2], axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
# vsplit --> axis 0
# hsplit --> axis 1

In [70]:
np.vsplit(ar3, [1])

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [65]:
np.hsplit(ar3, [1])

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

# Sorting of the Arrays

### sort()

In [71]:
ar4 = np.array([5,8,2,4,9,9,2,7,4,6,5])
ar4

array([5, 8, 2, 4, 9, 9, 2, 7, 4, 6, 5])

In [72]:
np.sort(ar4)

array([2, 2, 4, 4, 5, 5, 6, 7, 8, 9, 9])

In [74]:
ar4 # the original array is not changed

array([5, 8, 2, 4, 9, 9, 2, 7, 4, 6, 5])

In [75]:
ar4.sort()

In [ ]:
ar4 # it changed the original array when you use it directly without numpy

array([2, 2, 4, 4, 5, 5, 6, 7, 8, 9, 9])

In [77]:
ar5 = np.random.randint(1, 100, (4, 4))
ar5

array([[ 4, 57,  4, 60],
       [38,  2, 18, 76],
       [24, 95, 27, 44],
       [ 9, 63, 58, 36]], dtype=int32)

In [80]:
np.sort(ar5) # it sorts in rows

array([[ 4,  4, 57, 60],
       [ 2, 18, 38, 76],
       [24, 27, 44, 95],
       [ 9, 36, 58, 63]], dtype=int32)

# Numpy Indexing & Selection

### Bracket Indexing & Selection

In [81]:
arr1 = np.arange(12,21)
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [86]:
arr1.ndim # how many dimensinals 

1

In [85]:
arr1[3]

np.int64(15)

In [84]:
arr1[6]

np.int64(18)

In [83]:
arr1[-2]

np.int64(19)

In [82]:
arr1[2:5] # end point is excluded # slicing

array([14, 15, 16])

In [89]:
arr1[::-1] # reversed

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

In [88]:
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [90]:
arr1[::-3]  

array([20, 17, 14])

In [91]:
arr1[3:8:-2]

array([], dtype=int64)

### Indexing a 2D Array (Matrices)

In [92]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[0:, 1:] # it specifies the row before the comma and the column after it 

array([[2, 3],
       [5, 6],
       [8, 9]])

In [94]:
arr2[1, 2]

np.int64(6)

In [98]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

### Slicing a 2D Array (Matrices)

In [ ]:
my_ar1 = np.arange(0, 36).reshape(6, -1)
my_ar1 # 2D matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [111]:
my_ar1[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [113]:
my_ar1[2:5, 2:5]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [ ]:
my_ar1[2:5, [2, 4]]

array([[14, 16],
       [20, 22],
       [26, 28]])

In [115]:
my_ar1[2:5, 2::2]

array([[14, 16],
       [20, 22],
       [26, 28]])

### Fancy Indexing

In [116]:
my_ar1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [117]:
my_ar1[(2, 4, 5), (0, 2, 4)]

array([12, 26, 34])

In [118]:
my_ar1[2:, (1, 3, 5)]

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

### Selection on a Condition

In [119]:
np.random.seed(40) # we use this code so that everyone has the same random data
my_ar2 = np.random.randint(1, 50, size = (3, 4))
my_ar2

array([[ 7, 28,  8, 38],
       [ 2, 13,  8, 20],
       [32, 11, 20, 28]], dtype=int32)

In [120]:
my_ar2 > 15

array([[False,  True, False,  True],
       [False, False, False,  True],
       [ True, False,  True,  True]])

In [ ]:
my_ar2[my_ar2 > 15] # returns the numbers which are gerater than 15

array([28, 38, 20, 32, 20, 28], dtype=int32)

In [122]:
my_ar3 = np.arange(1, 51)
my_ar3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [124]:
my_ar3 % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False])

In [125]:
my_ar3[my_ar3 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])