In [1]:
import numpy as np

In [2]:
ar1 = np.array([3, 6, 8, 64, 3, 3, 8, 5, 3, 2])
ar1.max()

np.int64(64)

In [3]:
ar1.min()

np.int64(2)

In [4]:
ar1.size

10

In [6]:
ar2 = np.random.randint(0, 60, (4, 5))
ar2

array([[ 4, 59, 27, 27, 47],
       [43, 26, 10, 48, 35],
       [45, 10,  3, 45, 43],
       [46, 49, 53, 37, 20]], dtype=int32)

In [8]:
ar2.reshape(2, 10)

array([[ 4, 59, 27, 27, 47, 43, 26, 10, 48, 35],
       [45, 10,  3, 45, 43, 46, 49, 53, 37, 20]], dtype=int32)

In [13]:
ar2.reshape(-1, 2, 2)

array([[[ 4, 59],
        [27, 27]],

       [[47, 43],
        [26, 10]],

       [[48, 35],
        [45, 10]],

       [[ 3, 45],
        [43, 46]],

       [[49, 53],
        [37, 20]]], dtype=int32)

- create an array using arange function containing even numbers from 20 to 80 ,
- reshape it as 5 rows and 6  cols
- then take a copy of it

In [38]:
ar3 = np.arange(20, 80)
ar4 = ar3[ar3 % 2 == 0] 
ar4


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [66]:
ar5 = ar4.reshape(5,6)
ar5

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [67]:
ar4_copy = ar4.copy()
ar4_copy


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

- split the arr4 horizantally from half
- split the arr4 into 3 vertically(use array split)
- split the arr4 into 3 horizantally(use array split)
- split the arr4 horizantlly from index 5  (use split )

In [69]:
np.hsplit(ar5, 2)

[array([[20, 22, 24],
        [32, 34, 36],
        [44, 46, 48],
        [56, 58, 60],
        [68, 70, 72]]),
 array([[26, 28, 30],
        [38, 40, 42],
        [50, 52, 54],
        [62, 64, 66],
        [74, 76, 78]])]

In [70]:
np.array_split(ar5, 3)

[array([[20, 22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40, 42]]),
 array([[44, 46, 48, 50, 52, 54],
        [56, 58, 60, 62, 64, 66]]),
 array([[68, 70, 72, 74, 76, 78]])]

In [72]:
np.array_split(ar5, 3, axis = 1)

[array([[20, 22],
        [32, 34],
        [44, 46],
        [56, 58],
        [68, 70]]),
 array([[24, 26],
        [36, 38],
        [48, 50],
        [60, 62],
        [72, 74]]),
 array([[28, 30],
        [40, 42],
        [52, 54],
        [64, 66],
        [76, 78]])]

In [74]:
np.split(ar5,[5], axis=1)

[array([[20, 22, 24, 26, 28],
        [32, 34, 36, 38, 40],
        [44, 46, 48, 50, 52],
        [56, 58, 60, 62, 64],
        [68, 70, 72, 74, 76]]),
 array([[30],
        [42],
        [54],
        [66],
        [78]])]

In [77]:
ar5

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [78]:
ar5.T

array([[20, 32, 44, 56, 68],
       [22, 34, 46, 58, 70],
       [24, 36, 48, 60, 72],
       [26, 38, 50, 62, 74],
       [28, 40, 52, 64, 76],
       [30, 42, 54, 66, 78]])

In [81]:
ar6 = np.resize(ar5, (10, 10))
ar6

array([[20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [89]:
a = np.random.randint(1,10,4).reshape(2,2)
a

array([[7, 4],
       [9, 4]], dtype=int32)

In [88]:
b = np.random.randint(10,20,6).reshape(3,2)
b

array([[12, 19],
       [15, 11],
       [19, 16]], dtype=int32)

In [90]:
a_b = np.concatenate((a, b), axis = 0)
a_b

array([[ 7,  4],
       [ 9,  4],
       [12, 19],
       [15, 11],
       [19, 16]], dtype=int32)

In [93]:
ar5 = ar5.reshape(3, 10)
ar5

array([[20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78]])

In [100]:
ar5[1, 3]

np.int64(46)

In [ ]:
ar5[1:, 4:8]

array([[48, 50, 52, 54],
       [68, 70, 72, 74]])

In [103]:
ar5[0::2, ::2]

array([[20, 24, 28, 32, 36],
       [60, 64, 68, 72, 76]])

- Use the randint function to generate a numpy array with 40 elements between 1 and 100.
- Reshape it to 5, 8.
- Print the numbers greater than 40 in another array.
- Print the numbers divisible by 5 in another array.

In [104]:
ar6 = np.random.randint(1,100,40).reshape(5,8)
ar6

array([[ 8, 37, 36, 51, 38, 11, 61, 77],
       [97, 57, 69, 99, 56, 73, 64, 47],
       [34, 17,  9, 91, 50, 11, 89, 82],
       [17, 94, 83, 78, 21, 65, 77, 94],
       [89, 96, 44, 47, 46, 69, 23, 29]], dtype=int32)

In [106]:
ar6.reshape(5, 8)

array([[ 8, 37, 36, 51, 38, 11, 61, 77],
       [97, 57, 69, 99, 56, 73, 64, 47],
       [34, 17,  9, 91, 50, 11, 89, 82],
       [17, 94, 83, 78, 21, 65, 77, 94],
       [89, 96, 44, 47, 46, 69, 23, 29]], dtype=int32)

In [108]:
ar7 = ar6[ar6 > 40]
ar7

array([51, 61, 77, 97, 57, 69, 99, 56, 73, 64, 47, 91, 50, 89, 82, 94, 83,
       78, 65, 77, 94, 89, 96, 44, 47, 46, 69], dtype=int32)

In [109]:
ar8 = ar6[ar6 % 5 == 0]
ar8

array([50, 65], dtype=int32)

- Create a NumPy array of shape (3, 4) filled with ones.
- Create a NumPy array of shape (2, 5) filled with zeros.

In [115]:
np.ones((3,4)) +6

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [113]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
arr7 = np.arange(1,5)
arr7

array([1, 2, 3, 4])

In [118]:
np.ones((3,4)) + 6 + arr7

array([[ 8.,  9., 10., 11.],
       [ 8.,  9., 10., 11.],
       [ 8.,  9., 10., 11.]])

In [122]:
x = np.ones_like(ar5)
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [124]:
np.linspace(20, 40, 10)

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])